title: "Juan José Jaramillo"
email: jjj.1998@hotmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Base website for an awsome programmer, it looks humble but just you wait
baseurl: "/JuanJoseJ.github.io" 
url: "https://JuanJoseJ.github.io" 
twitter_username: JJJaramillo
github_username:  JuanJoseJ

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
